name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Code
      uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.1.20452.10'
    - name: Install Dependencies
      run: dotnet restore
      env:
        DOTNET_NOLOGO: true
    - name: Create Nuget Package
      run: dotnet pack --nologo --configuration Release --no-restore --output artifacts -p:Version=${{ github.event.release.tag_name }}
